### ISSUE TITLE
laser goes straight down in middle of job

### ISSUE THREAD

**Issue by quillford** [t-oster/LibLaserCut#31] opened 2015-10-06 18:42 UTC
It will be in the middle of a job and then suddenly shoot straight downward then continue back to the job. I haven't looked at the gcode yet. I'll get a video of it up soon and get the gcode. I'm using Marlin on the smoothieboard branch.

**Comment by t-oster** [comment] 2015-10-07 08:29
are you sure that there is not a "bad pixel" in your drawing? or does it happen on different jobs?

**Comment by mgmax** [comment] 2017-05-14 08:22
@quillford As the bug seems to be not reproducable, could you please close this bugreport? Thanks.

**Closed** 2017-05-15 16:10 UTC
